-- (1) Check warehouse usage
SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
WHERE WAREHOUSE_NAME = 'ETL_WH'
ORDER BY START_TIME DESC;

-- (2) Check Snowpipe usage
SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.PIPE_USAGE_HISTORY
ORDER BY START_TIME DESC; -- currently empty as snowpipe to S3/ADLS not implemented
